import type { Metadata, Viewport } from "next";
import Localfont from "next/font/local";
import "./globals.css";
import TenstackProvider from "@/util/config/Providers/TenstackProvider";
import NextNProgressWrapper from "@/components/Layout/NextNProgressWrapper";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
const yekan = Localfont({
  src: [
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-SemiBold.ttf",
      weight: "600",
      style: "SemiBold",
    },
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-Regular.ttf",
      weight: "500",
      style: "Regular",
    },
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-Light.ttf",
      weight: "300",
      style: "Light",
    },
  ],
});
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={yekan.className} >
        <NextNProgressWrapper>
          <TenstackProvider>

            {children}

          </TenstackProvider>
        </NextNProgressWrapper>
      </body>
    </html>
  );
}
