import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Localfont from "next/font/local";
import "./globals.css";
import TenstackProvider from "@/util/Providers/TenstackProvider";

const yekan = Localfont({
  src: [
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-SemiBold.ttf",
      weight: "600",
      style: "SemiBold",
    },
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-Regular.ttf",
      weight: "500",
      style: "Regular",
    },
    {
      path: "../public/Fonts/Yekan Bakh FaNum/TTF/YekanBakhFaNum-Light.ttf",
      weight: "300",
      style: "Light",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TenstackProvider>
        <body className={yekan.className}>{children}</body>
      </TenstackProvider>
    </html>
  );
}
